[18/11/2018 04:22] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\audio.py", line 310, in <module>
    class Audio:
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\audio.py", line 1190, in Audio
    async def audioset_notifychannel(self, ctx, channel: discord.Channel):
AttributeError: module 'discord' has no attribute 'Channel'
[18/11/2018 04:22] ERROR red load_cogs 573: You need the imgurpython module to use this.
pip3 install imgurpython
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 700, in load_extension
    lib.setup(self)
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\image.py", line 165, in setup
    raise RuntimeError("You need the imgurpython module to use this.\n"
RuntimeError: You need the imgurpython module to use this.
pip3 install imgurpython
[18/11/2018 04:22] ERROR red load_cogs 573: module 'discord' has no attribute 'Channel'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\mod.py", line 92, in <module>
    class Mod:
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\mod.py", line 147, in Mod
    async def modlog(self, ctx, channel : discord.Channel=None):
AttributeError: module 'discord' has no attribute 'Channel'
[18/11/2018 04:22] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[18/11/2018 04:24] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
[18/11/2018 05:00] ERROR red on_command_error 369: Exception in command 'snacktime'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Ryan\Desktop\Red-DiscordBot\cogs\snacktime.py", line 223, in snacktime
    scid = ctx.message.server.id+"-"+ctx.message.channel.id
AttributeError: 'NoneType' object has no attribute 'id'
